<?php
class Question {
    private $id_question;
    private $id_client;
    private $question_text;
    private $created_at;
    
    // Constructor without id_question, which is auto-generated by the database
    public function __construct(int $id_client, string $question_text, DateTime $created_at = null) {
        $this->id_client = $id_client;
        $this->question_text = $question_text;
        $this->created_at = $created_at ?? new DateTime(); // Default to current date/time if not provided
    }

    // Method to save the question to the database
    public function save($pdo) {
        $stmt = $pdo->prepare("INSERT INTO question (id_client, question_text, created_at) VALUES (?, ?, ?)");
        $stmt->execute([
            $this->id_client,
            $this->question_text,
            $this->created_at->format('Y-m-d H:i:s') // Format DateTime for MySQL
        ]);
        $this->id_question = $pdo->lastInsertId(); // Set the id after inserting
    }

    // Static method to get all questions from the database
    public static function getAll($pdo) {
        $stmt = $pdo->query("SELECT * FROM question ORDER BY created_at DESC");
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }

    // Getters
    public function getIdQuestion(): int {
        return $this->id_question;
    }

    public function getIdClient(): int {
        return $this->id_client;
    }

    public function getQuestionText(): string {
        return $this->question_text;
    }

    public function getCreatedAt(): DateTime {
        return $this->created_at;
    }

    // Setters
    public function setIdQuestion(int $id_question): void {
        $this->id_question = $id_question;
    }

    public function setIdClient(int $id_client): void {
        $this->id_client = $id_client;
    }

    public function setQuestionText(string $question_text): void {
        $this->question_text = $question_text;
    }

    public function setCreatedAt(DateTime $created_at): void {
        $this->created_at = $created_at;
    }
}
?>
